Pagination
oomer9/pokedex pull request #7
Opened 2024-03-22 17:45 UTC by aomer03

pagination was implemented

2024-03-22 19:10 UTC, oomer9 commented on src/components/listNavBar/index.tsx
> -  const { page, totalPages, setPageNumber, setPageSize, pageSize } = props;
Did you remove pageSize from where it was being passed it?

2024-04-02 16:22 UTC, aomer03 commented on src/components/listNavBar/index.tsx
> -  const { page, totalPages, setPageNumber, setPageSize, pageSize } = props;
page size is being passed now

2024-04-02 16:38 UTC, oomer9 requested changes

2024-04-02 16:38 UTC, oomer9 commented on src/components/listNavBar/index.tsx
> +  setPageSize: Dispatch<SetStateAction<number>>;
IF  setPageSize and pageSize are not being used then they can be removed from props

2024-04-03 17:51 UTC, oomer9 approved these changes

2024-04-03 17:56 UTC, merged